services:
  # 1. Backend API (FastAPI)
  - type: web
    name: veda-backend
    env: python
    buildCommand: pip install -r veda_backend/requirements.txt && python veda_backend/seed_db.py
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker veda_backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false # Anda akan memasukkan Service URL dari Aiven MySQL secara manual

  # 2. Frontend (React + Vite)
  - type: web
    name: veda-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: veda_frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://veda-backend.onrender.com/api
